services: # Palabra clave de Docker Compose.
  nginx: # Palabra no clave, descriptiva de un servicio.
    container_name: nginx-3
    image: nginx:alpine # Imagen a extraer desde Docker Hub.
    restart: always
    ports: # Mapeado de puertos entre la máquina real y el contenedor.
      - "80:80"
    networks: # Este servicio pertenece a la red: internal
      - internal
    volumes:
      - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/nala
  php:
    container_name: php-3
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      - internal
    volumes:
      - ./:/var/www/nala
  mysql:
    container_name: mysql-3
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: nala
      MYSQL_ROOT_PASSWORD: 'pw123'
    ports:
      - '33064:3306'
    expose:
      - '3306'
    volumes:
      - ./database/schema.sql:/schema.sql
      - ./database/dumps/nala_dump230905.sql:/dump.sql
      - db:/var/lib/mysql
    networks:
      - internal

volumes:
  db:
    driver: local

networks:
  internal: # Nombre de la red.
    driver: bridge # Modo de conexión.